#!/usr/bin/env bash
set -e

echo "Running pre-commit checks..."

echo "=> golangci-lint"
golangci-lint run ./...

echo "=> go build"
go build -v .

echo "=> go test"
go test -race ./...

echo "All checks passed."
